### ISSUE TITLE
投递失败：failed:SMTPServerDisconnected('please run connect() first‘,)

### ISSUE THREAD

**Issue by Sciroccogti** [KUNzfw/KindleEar-Docker#2]
```python
INFO 2021-07-13 15:49:56,247 resources.py:49] Serializing resources...
INFO 2021-07-13 15:49:56,260 mobioutput.py:149] Creating MOBI 6 output
INFO 2021-07-13 15:49:57,588 manglecase.py:34] Applying case-transforming CSS...
INFO 2021-07-13 15:49:57,610 parse_utils.py:302] Forcing toc.html into XHTML namespace
INFO 2021-07-13 15:50:08,744 mail_stub.py:170] MailService.Send
From: x@126.com
To: x@kindle.cn
To: x@126.com
Subject: KindleEar 2021-07-13_23-50
Body:
Content-type: text/plain
Data length: 22
Attachment:
File name: KindleEar-Unraid(2021-07-13_23-50).mobi
Data length: 19165970
ERROR 2021-07-13 15:50:39,400 api_server.py:385] Exception while handling mail.Send()

Traceback (most recent call last):
File "/app/google_appengine/google/appengine/tools/devappserver2/api_server.py", line 353, in _handle_POST
api_response = _execute_request(request).Encode()
File "/app/google_appengine/google/appengine/tools/devappserver2/api_server.py", line 169, in _execute_request
make_request()
File "/app/google_appengine/google/appengine/tools/devappserver2/api_server.py", line 164, in make_request
request_id)
File "/app/google_appengine/google/appengine/api/apiproxy_stub.py", line 151, in MakeSyncCall
method(request, response)
File "/app/google_appengine/google/appengine/api/mail_stub.py", line 374, in _Send
self._SendSMTP(mime_message, smtp_lib)
File "/app/google_appengine/google/appengine/api/mail_stub.py", line 295, in _SendSMTP
smtp.quit()
File "/usr/lib/python2.7/smtplib.py", line 773, in quit
res = self.docmd("quit")
File "/usr/lib/python2.7/smtplib.py", line 394, in docmd
self.putcmd(cmd, args)
File "/usr/lib/python2.7/smtplib.py", line 342, in putcmd
self.send(str)
File "/usr/lib/python2.7/smtplib.py", line 334, in send
raise SMTPServerDisconnected('please run connect() first')
SMTPServerDisconnected: please run connect() first

WARNING 2021-07-13 15:50:39,409 BaseHandler.py:175] sendmail to [u'x@kindle.cn', u'x@126.com'] failed:SMTPServerDisconnected('please run connect() first',)
```

**Comment by Sciroccogti** [comment]
似乎是因为 `KINDLEEAR_DOMAIN` 设置错误。。不过都自建了，应该不需要这个参数才对欸

**Comment by coekfung** [comment]
> 似乎是因为 `KINDLEEAR_DOMAIN` 设置错误。。不过都自建了，应该不需要这个参数才对欸

可以告诉我你的KINDLEEAR_DOMAIN项配置了什么吗？另外，这个项目本质上是在docker里面跑了一个gae的开发环境，所以一切配置都要按照gae的要求进行。

**Comment by coekfung** [comment]
是配置错误的问题，请正确配置，先close了

**Comment by cikiChe** [comment]
遇到一摸一样的问题了。我也是使用的163

**Comment by cikiChe** [comment]
确实是配置问题

163 需要使用 授权码登录 
我使用了25 端口

**Comment by GreyFlorence** [comment]
我也遇到一样的问题，不知道大家解决了吗

**Comment by coekfung** [comment]
> 我也遇到一样的问题，不知道大家解决了吗

如遇问题请先检查配置，如果还是不行可以将配置里的信息进行模糊处理后贴上来
