### ISSUE TITLE
大佬牛逼

### ISSUE THREAD

**Issue by cikiChe** [KUNzfw/KindleEar-Docker#3]
刚刚吃泡面的时候，看到了这个板子。

于是又想来折腾了，但是搞不定 Google gae 。因为我死活开通不了那个结算方式。

等下就来试试大佬的东西

**Comment by cikiChe** [comment]
环境：本地vm 上搭建 centos7

问题日志：
[root@myhost data]# docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED              STATUS                         PORTS               NAMES
5c459a3a906c        3ff8a971c04a        "/bin/sh -c 'pytho..."   About a minute ago   Restarting (0) 3 seconds ago                       kindleear
[root@myhost data]# docker logs 5c
sed: /app/KindleEar/config.py: No such file or directory
sed: /app/KindleEar/config.py: No such file or directory
Traceback (most recent call last):
  File "/app/google_appengine/dev_appserver.py", line 96, in <module>
    _run_file(__file__, globals())
  File "/app/google_appengine/dev_appserver.py", line 90, in _run_file
    execfile(_PATHS.script_file(script_name), globals_)
  File "/app/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 613, in <module>
    main()
  File "/app/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 601, in main
    dev_server.start(options)
  File "/app/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 277, in start
    env_variables=parsed_env_variables)
  File "/app/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 940, in __init__
    env_variables)
  File "/app/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 139, in __init__
    self._config_path)
  File "/app/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 501, in _parse_configuration
    with open(configuration_path) as f:
IOError: [Errno 2] No such file or directory: '/app/KindleEar/app.yaml'
sed: /app/KindleEar/config.py: No such file or directory
sed: /app/KindleEar/config.py: No such file or directory
Traceback (most recent call last):
  File "/app/google_appengine/dev_appserver.py", line 96, in <module>
    _run_file(__file__, globals())
  File "/app/google_appengine/dev_appserver.py", line 90, in _run_file
    execfile(_PATHS.script_file(script_name), globals_)
  File "/app/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 613, in <module>
    main()
  File "/app/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 601, in main
    dev_server.start(options)
  File "/app/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 277, in start
    env_variables=parsed_env_variables)
  File "/app/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 940, in __init__
    env_variables)
  File "/app/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 139, in __init__
    self._config_path)
  File "/app/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 501, in _parse_configuration
    with open(configuration_path) as f:
IOError: [Errno 2] No such file or directory: '/app/KindleEar/app.yaml'
sed: /app/KindleEar/config.py: No such file or directory
sed: /app/KindleEar/config.py: No such file or directory
Traceback (most recent call last):
  File "/app/google_appengine/dev_appserver.py", line 96, in <module>
    _run_file(__file__, globals())
  File "/app/google_appengine/dev_appserver.py", line 90, in _run_file
    execfile(_PATHS.script_file(script_name), globals_)
  File "/app/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 613, in <module>
    main()
  File "/app/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 601, in main
    dev_server.start(options)
  File "/app/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 277, in start
    env_variables=parsed_env_variables)
  File "/app/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 940, in __init__
    env_variables)
  File "/app/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 139, in __init__
    self._config_path)
  File "/app/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 501, in _parse_configuration
    with open(configuration_path) as f:
IOError: [Errno 2] No such file or directory: '/app/KindleEar/app.yaml'
sed: /app/KindleEar/config.py: No such file or directory
sed: /app/KindleEar/config.py: No such file or directory
Traceback (most recent call last):
  File "/app/google_appengine/dev_appserver.py", line 96, in <module>
    _run_file(__file__, globals())
  File "/app/google_appengine/dev_appserver.py", line 90, in _run_file
    execfile(_PATHS.script_file(script_name), globals_)
  File "/app/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 613, in <module>
    main()
  File "/app/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 601, in main
    dev_server.start(options)
  File "/app/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 277, in start
    env_variables=parsed_env_variables)
  File "/app/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 940, in __init__
    env_variables)
  File "/app/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 139, in __init__
    self._config_path)
  File "/app/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 501, in _parse_configuration
    with open(configuration_path) as f:
IOError: [Errno 2] No such file or directory: '/app/KindleEar/app.yaml'
sed: /app/KindleEar/config.py: No such file or directory
sed: /app/KindleEar/config.py: No such file or directory
Traceback (most recent call last):
  File "/app/google_appengine/dev_appserver.py", line 96, in <module>
    _run_file(__file__, globals())
  File "/app/google_appengine/dev_appserver.py", line 90, in _run_file
    execfile(_PATHS.script_file(script_name), globals_)
  File "/app/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 613, in <module>
    main()
  File "/app/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 601, in main
    dev_server.start(options)
  File "/app/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 277, in start
    env_variables=parsed_env_variables)
  File "/app/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 940, in __init__
    env_variables)
  File "/app/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 139, in __init__
    self._config_path)
  File "/app/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 501, in _parse_configuration
    with open(configuration_path) as f:
IOError: [Errno 2] No such file or directory: '/app/KindleEar/app.yaml'
sed: /app/KindleEar/config.py: No such file or directory
sed: /app/KindleEar/config.py: No such file or directory
Traceback (most recent call last):
  File "/app/google_appengine/dev_appserver.py", line 96, in <module>
    _run_file(__file__, globals())
  File "/app/google_appengine/dev_appserver.py", line 90, in _run_file
    execfile(_PATHS.script_file(script_name), globals_)
  File "/app/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 613, in <module>
    main()
  File "/app/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 601, in main
    dev_server.start(options)
  File "/app/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 277, in start
    env_variables=parsed_env_variables)
  File "/app/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 940, in __init__
    env_variables)
  File "/app/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 139, in __init__
    self._config_path)
  File "/app/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 501, in _parse_configuration
    with open(configuration_path) as f:
IOError: [Errno 2] No such file or directory: '/app/KindleEar/app.yaml'
sed: /app/KindleEar/config.py: No such file or directory
sed: /app/KindleEar/config.py: No such file or directory
Traceback (most recent call last):
  File "/app/google_appengine/dev_appserver.py", line 96, in <module>
    _run_file(__file__, globals())
  File "/app/google_appengine/dev_appserver.py", line 90, in _run_file
    execfile(_PATHS.script_file(script_name), globals_)
  File "/app/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 613, in <module>
    main()
  File "/app/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 601, in main
    dev_server.start(options)
  File "/app/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 277, in start
    env_variables=parsed_env_variables)
  File "/app/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 940, in __init__
    env_variables)
  File "/app/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 139, in __init__
    self._config_path)
  File "/app/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 501, in _parse_configuration
    with open(configuration_path) as f:
IOError: [Errno 2] No such file or directory: '/app/KindleEar/app.yaml'
sed: /app/KindleEar/config.py: No such file or directory
sed: /app/KindleEar/config.py: No such file or directory
Traceback (most recent call last):
  File "/app/google_appengine/dev_appserver.py", line 96, in <module>
    _run_file(__file__, globals())
  File "/app/google_appengine/dev_appserver.py", line 90, in _run_file
    execfile(_PATHS.script_file(script_name), globals_)
  File "/app/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 613, in <module>
    main()
  File "/app/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 601, in main
    dev_server.start(options)
  File "/app/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 277, in start
    env_variables=parsed_env_variables)
  File "/app/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 940, in __init__
    env_variables)
  File "/app/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 139, in __init__
    self._config_path)
  File "/app/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 501, in _parse_configuration
    with open(configuration_path) as f:
IOError: [Errno 2] No such file or directory: '/app/KindleEar/app.yaml'
sed: /app/KindleEar/config.py: No such file or directory
sed: /app/KindleEar/config.py: No such file or directory
Traceback (most recent call last):
  File "/app/google_appengine/dev_appserver.py", line 96, in <module>
    _run_file(__file__, globals())
  File "/app/google_appengine/dev_appserver.py", line 90, in _run_file
    execfile(_PATHS.script_file(script_name), globals_)
  File "/app/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 613, in <module>
    main()
  File "/app/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 601, in main
    dev_server.start(options)
  File "/app/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 277, in start
    env_variables=parsed_env_variables)
  File "/app/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 940, in __init__
    env_variables)
  File "/app/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 139, in __init__
    self._config_path)
  File "/app/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 501, in _parse_configuration
    with open(configuration_path) as f:
IOError: [Errno 2] No such file or directory: '/app/KindleEar/app.yaml'
sed: /app/KindleEar/config.py: No such file or directory
sed: /app/KindleEar/config.py: No such file or directory
Traceback (most recent call last):
  File "/app/google_appengine/dev_appserver.py", line 96, in <module>
    _run_file(__file__, globals())
  File "/app/google_appengine/dev_appserver.py", line 90, in _run_file
    execfile(_PATHS.script_file(script_name), globals_)
  File "/app/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 613, in <module>
    main()
  File "/app/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 601, in main
    dev_server.start(options)
  File "/app/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 277, in start
    env_variables=parsed_env_variables)
  File "/app/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 940, in __init__
    env_variables)
  File "/app/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 139, in __init__
    self._config_path)
  File "/app/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 501, in _parse_configuration
    with open(configuration_path) as f:
IOError: [Errno 2] No such file or directory: '/app/KindleEar/app.yaml'

**Comment by cikiChe** [comment]
找到问题了

> 环境：本地vm 上搭建 centos7
> 
> 问题日志： [root@myhost data]# docker ps CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES 5c459a3a906c 3ff8a971c04a "/bin/sh -c 'pytho..." About a minute ago Restarting (0) 3 seconds ago kindleear [root@myhost data]# docker logs 5c sed: /app/KindleEar/config.py: No such file or directory sed: /app/KindleEar/config.py: No such file or directory Traceback (most recent call last): File "/app/google_appengine/dev_appserver.py", line 96, in _run_file(**file**, globals()) File "/app/google_appengine/dev_appserver.py", line 90, in _run_file execfile(_PATHS.script_file(script_name), globals_) File "/app/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 613, in main() File "/app/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 601, in main dev_server.start(options) File "/app/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 277, in start env_variables=parsed_env_variables) File "/app/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 940, in **init** env_variables) File "/app/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 139, in **init** self._config_path) File "/app/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 501, in _parse_configuration with open(configuration_path) as f: IOError: [Errno 2] No such file or directory: '/app/KindleEar/app.yaml' sed: /app/KindleEar/config.py: No such file or directory sed: /app/KindleEar/config.py: No such file or directory Traceback (most recent call last): File "/app/google_appengine/dev_appserver.py", line 96, in _run_file(**file**, globals()) File "/app/google_appengine/dev_appserver.py", line 90, in _run_file execfile(_PATHS.script_file(script_name), globals_) File "/app/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 613, in main() File "/app/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 601, in main dev_server.start(options) File "/app/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 277, in start env_variables=parsed_env_variables) File "/app/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 940, in **init** env_variables) File "/app/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 139, in **init** self._config_path) File "/app/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 501, in _parse_configuration with open(configuration_path) as f: IOError: [Errno 2] No such file or directory: '/app/KindleEar/app.yaml' sed: /app/KindleEar/config.py: No such file or directory sed: /app/KindleEar/config.py: No such file or directory Traceback (most recent call last): File "/app/google_appengine/dev_appserver.py", line 96, in _run_file(**file**, globals()) File "/app/google_appengine/dev_appserver.py", line 90, in _run_file execfile(_PATHS.script_file(script_name), globals_) File "/app/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 613, in main() File "/app/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 601, in main dev_server.start(options) File "/app/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 277, in start env_variables=parsed_env_variables) File "/app/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 940, in **init** env_variables) File "/app/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 139, in **init** self._config_path) File "/app/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 501, in _parse_configuration with open(configuration_path) as f: IOError: [Errno 2] No such file or directory: '/app/KindleEar/app.yaml' sed: /app/KindleEar/config.py: No such file or directory sed: /app/KindleEar/config.py: No such file or directory Traceback (most recent call last): File "/app/google_appengine/dev_appserver.py", line 96, in _run_file(**file**, globals()) File "/app/google_appengine/dev_appserver.py", line 90, in _run_file execfile(_PATHS.script_file(script_name), globals_) File "/app/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 613, in main() File "/app/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 601, in main dev_server.start(options) File "/app/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 277, in start env_variables=parsed_env_variables) File "/app/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 940, in **init** env_variables) File "/app/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 139, in **init** self._config_path) File "/app/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 501, in _parse_configuration with open(configuration_path) as f: IOError: [Errno 2] No such file or directory: '/app/KindleEar/app.yaml' sed: /app/KindleEar/config.py: No such file or directory sed: /app/KindleEar/config.py: No such file or directory Traceback (most recent call last): File "/app/google_appengine/dev_appserver.py", line 96, in _run_file(**file**, globals()) File "/app/google_appengine/dev_appserver.py", line 90, in _run_file execfile(_PATHS.script_file(script_name), globals_) File "/app/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 613, in main() File "/app/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 601, in main dev_server.start(options) File "/app/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 277, in start env_variables=parsed_env_variables) File "/app/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 940, in **init** env_variables) File "/app/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 139, in **init** self._config_path) File "/app/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 501, in _parse_configuration with open(configuration_path) as f: IOError: [Errno 2] No such file or directory: '/app/KindleEar/app.yaml' sed: /app/KindleEar/config.py: No such file or directory sed: /app/KindleEar/config.py: No such file or directory Traceback (most recent call last): File "/app/google_appengine/dev_appserver.py", line 96, in _run_file(**file**, globals()) File "/app/google_appengine/dev_appserver.py", line 90, in _run_file execfile(_PATHS.script_file(script_name), globals_) File "/app/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 613, in main() File "/app/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 601, in main dev_server.start(options) File "/app/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 277, in start env_variables=parsed_env_variables) File "/app/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 940, in **init** env_variables) File "/app/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 139, in **init** self._config_path) File "/app/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 501, in _parse_configuration with open(configuration_path) as f: IOError: [Errno 2] No such file or directory: '/app/KindleEar/app.yaml' sed: /app/KindleEar/config.py: No such file or directory sed: /app/KindleEar/config.py: No such file or directory Traceback (most recent call last): File "/app/google_appengine/dev_appserver.py", line 96, in _run_file(**file**, globals()) File "/app/google_appengine/dev_appserver.py", line 90, in _run_file execfile(_PATHS.script_file(script_name), globals_) File "/app/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 613, in main() File "/app/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 601, in main dev_server.start(options) File "/app/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 277, in start env_variables=parsed_env_variables) File "/app/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 940, in **init** env_variables) File "/app/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 139, in **init** self._config_path) File "/app/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 501, in _parse_configuration with open(configuration_path) as f: IOError: [Errno 2] No such file or directory: '/app/KindleEar/app.yaml' sed: /app/KindleEar/config.py: No such file or directory sed: /app/KindleEar/config.py: No such file or directory Traceback (most recent call last): File "/app/google_appengine/dev_appserver.py", line 96, in _run_file(**file**, globals()) File "/app/google_appengine/dev_appserver.py", line 90, in _run_file execfile(_PATHS.script_file(script_name), globals_) File "/app/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 613, in main() File "/app/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 601, in main dev_server.start(options) File "/app/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 277, in start env_variables=parsed_env_variables) File "/app/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 940, in **init** env_variables) File "/app/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 139, in **init** self._config_path) File "/app/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 501, in _parse_configuration with open(configuration_path) as f: IOError: [Errno 2] No such file or directory: '/app/KindleEar/app.yaml' sed: /app/KindleEar/config.py: No such file or directory sed: /app/KindleEar/config.py: No such file or directory Traceback (most recent call last): File "/app/google_appengine/dev_appserver.py", line 96, in _run_file(**file**, globals()) File "/app/google_appengine/dev_appserver.py", line 90, in _run_file execfile(_PATHS.script_file(script_name), globals_) File "/app/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 613, in main() File "/app/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 601, in main dev_server.start(options) File "/app/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 277, in start env_variables=parsed_env_variables) File "/app/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 940, in **init** env_variables) File "/app/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 139, in **init** self._config_path) File "/app/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 501, in _parse_configuration with open(configuration_path) as f: IOError: [Errno 2] No such file or directory: '/app/KindleEar/app.yaml' sed: /app/KindleEar/config.py: No such file or directory sed: /app/KindleEar/config.py: No such file or directory Traceback (most recent call last): File "/app/google_appengine/dev_appserver.py", line 96, in _run_file(**file**, globals()) File "/app/google_appengine/dev_appserver.py", line 90, in _run_file execfile(_PATHS.script_file(script_name), globals_) File "/app/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 613, in main() File "/app/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 601, in main dev_server.start(options) File "/app/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 277, in start env_variables=parsed_env_variables) File "/app/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 940, in **init** env_variables) File "/app/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 139, in **init** self._config_path) File "/app/google_appengine/google/appengine/tools/devappserver2/application_configuration.py", line 501, in _parse_configuration with open(configuration_path) as f: IOError: [Errno 2] No such file or directory: '/app/KindleEar/app.yaml'

找到问题了，原来是昨天网络差的时候，没有成功下载完代码

**Comment by cikiChe** [comment]
这很难受
镜像拉不下来，git clone 无法克隆那个目录，zip下载也没有那个目录
全局代理，不代理都不行

**Comment by cikiChe** [comment]
忍着龟速下载镜像，最后运行起来了。
不懂就问，我想想问问大佬，那个目录仓库你是怎么弄成这种引用的方式的
感谢大佬，很好用

**Comment by coekfung** [comment]
> 忍着龟速下载镜像，最后运行起来了。 不懂就问，我想想问问大佬，那个目录仓库你是怎么弄成这种引用的方式的 感谢大佬，很好用

引用是git的submodule功能。其实我就是一个搬运工，把gae开发环境打包进docker罢了。既然问题解决了就先close了。
