### ISSUE TITLE
一直推送失败

### ISSUE THREAD

**Issue by 6uu1** [KUNzfw/KindleEar-Docker#7]
部署在自己的vps上的

日志：
```````py
RROR    2023-08-25 15:14:07,771 api_server.py:385] Exception while handling mail.Send()
Traceback (most recent call last):
  File "/app/google_appengine/google/appengine/tools/devappserver2/api_server.py", line 353, in _handle_POST
    api_response = _execute_request(request).Encode()
  File "/app/google_appengine/google/appengine/tools/devappserver2/api_server.py", line 169, in _execute_request
    make_request()
  File "/app/google_appengine/google/appengine/tools/devappserver2/api_server.py", line 164, in make_request
    request_id)
  File "/app/google_appengine/google/appengine/api/apiproxy_stub.py", line 151, in MakeSyncCall
    method(request, response)
  File "/app/google_appengine/google/appengine/api/mail_stub.py", line 374, in _Send
    self._SendSMTP(mime_message, smtp_lib)
  File "/app/google_appengine/google/appengine/api/mail_stub.py", line 293, in _SendSMTP
    smtp.sendmail(mime_message['From'], tos, mime_message.as_string())
  File "/usr/lib/python2.7/smtplib.py", line 744, in sendmail
    senderrs[each] = (code, resp)
TypeError: unhashable instance

WARNING  2023-08-25 15:14:07,773 BaseHandler.py:175] sendmail to [u'xxx@kindle.com', u'xxx@qq.com'] failed:TypeError('unhashable instance',). 

`````

**Comment by coekfung** [comment]
应该为上游应用的错误。https://bugs.python.org/issue22965
看到你的日志中传的是`[u'xxx@kindle.com', u'xxx@qq.com']`，这个配置的类型不是str可能导致app engine和smtplib出现问题。
